import assert from "node:assert/strict";
import test from "node:test";
import {readFile} from "node:fs/promises";
import {Window} from "happy-dom";
const source=await readFile(new URL('../scripts/lib/beebot-proactive-followup.snippet.js',import.meta.url),'utf8');
const tick=()=>new Promise(resolve=>setTimeout(resolve,10));
function store(value){const subs=new Set();return {get:()=>value,set(next){value=next;subs.forEach(fn=>fn());},subscribe(fn){subs.add(fn);return()=>subs.delete(fn);},count:()=>subs.size};}
async function boot(t){const win=new Window({url:'https://beebot.test'});win.__sandUiLanguage='zh';win.document.body.innerHTML='<textarea>Third draft</textarea><aside><div data-beebot-library-host="bot"></div></aside>';const selection=store({currentAgentId:'bot'}),connection=store({transport:'up'}),resources=new Map(),calls=[];let createResult;
 const get=id=>{if(!resources.has(id))resources.set(id,store({status:'empty'}));return resources.get(id);};
 const runtime={selection:{snapshots:selection},connection:{snapshots:connection},automations:{snapshotsFor:get,create:async(id,spec)=>{calls.push(['create',id,JSON.parse(JSON.stringify(spec))]);if(createResult)return await createResult;const routine={id:'standing-order',...spec};get(id).set({status:'ready',value:[routine]});return routine;},setEnabled:async(id,routineId,enabled)=>{calls.push(['enabled',id,routineId,enabled]);const current=get(id).get().value.map(r=>({...r,isEnabled:enabled}));get(id).set({status:'ready',value:current});},refresh:id=>calls.push(['refresh',id])}};
 win.runtime=runtime;win.eval(source+';RBindProactiveFollowup(window.runtime)');await tick();t.after(async()=>{win.__beebotFollowup?.dispose();await win.happyDOM.close();});return {win,runtime,selection,connection,get,calls,result:p=>createResult=p,root:()=>win.document.querySelector('#beebot-proactive-followup'),action:()=>win.document.querySelector('#beebot-proactive-followup button'),async select(id){win.document.querySelector('[data-beebot-library-host]').setAttribute('data-beebot-library-host',id);selection.set({currentAgentId:id});await tick();}};}
test('single Bot and Group explicitly enable one Node-owned standing order; no background creation or draft change',async t=>{for(const id of ['bot','group']){const ui=await boot(t);await ui.select(id);assert.equal(ui.calls.length,0);ui.action().click();await tick();assert.equal(ui.calls.length,1);const [,owner,spec]=ui.calls[0];assert.equal(owner,id);assert.equal(spec.purpose,'proactive-followup');assert.equal(spec.executionOwner,'local');assert.equal(spec.trigger.schedule,'17 9-17 * * 1-5');assert.match(spec.prompt,/finish quietly/);assert.match(spec.prompt,/uncertain external operation/);assert.match(spec.prompt,/do not impersonate peers/);assert.match(ui.root().textContent,/暂停跟进/);assert.equal(ui.win.document.querySelector('textarea').value,'Third draft');}});
test('an existing standing order is paused and resumed without replacement or duplicate creation',async t=>{const ui=await boot(t);ui.get('bot').set({status:'ready',value:[{id:'customized',purpose:'proactive-followup',executionOwner:'local',isEnabled:true,trigger:{type:'cron',schedule:'17 9 * * 1-5'},prompt:'User instruction'}]});await tick();ui.action().click();await tick();ui.action().click();await tick();assert.deepEqual(ui.calls,[['enabled','bot','customized',false],['enabled','bot','customized',true]]);});
test('an unconfirmed save blocks double submit and reloads instead of replaying the command',async t=>{const ui=await boot(t);ui.result(Promise.reject(Error('private credential error')));ui.action().click();ui.action().click();await tick();assert.equal(ui.calls.length,1);assert.ok(ui.action().disabled);assert.match(ui.root().textContent,/保存结果未确认/);assert.doesNotMatch(ui.root().textContent,/credential/);ui.root().querySelectorAll('button')[1].click();await tick();assert.deepEqual(ui.calls[1],['refresh','bot']);assert.equal(ui.calls.filter(c=>c[0]==='create').length,1);});
test('stale success cannot cross selection or connection generation',async t=>{for(const kind of ['selection','connection']){const ui=await boot(t),gate=Promise.withResolvers();ui.result(gate.promise);ui.action().click();await tick();if(kind==='selection')await ui.select('group');else ui.connection.set({transport:'down'});await tick();gate.resolve({id:'late',purpose:'proactive-followup',executionOwner:'local'});await tick();assert.doesNotMatch(ui.root().textContent,/设置已保存/);assert.equal(ui.win.document.querySelector('textarea').value,'Third draft');if(kind==='connection')assert.ok(ui.action().disabled);}});
test('remote selection hides local standing orders and unavailable states cannot create',async t=>{const ui=await boot(t);ui.get('bot').set({status:'unavailable'});await tick();assert.ok(ui.action().disabled);ui.win.document.body.dataset.beebotRemoteActive='true';ui.win.dispatchEvent(new ui.win.Event('beebot-node-selection'));await tick();assert.equal(ui.root(),null);assert.equal(ui.calls.length,0);});
test('language and pane lifetime preserve current drafts, and closing releases routine subscription',async t=>{const ui=await boot(t),draft=ui.win.document.querySelector('textarea');draft.focus();draft.setSelectionRange(2,5);ui.win.__sandUiLanguage='en';ui.win.dispatchEvent(new ui.win.Event('sand-ui-language-changed'));await tick();assert.match(ui.root().textContent,/Proactive follow-up/);assert.equal(ui.win.document.activeElement,draft);assert.equal(draft.selectionStart,2);assert.equal(ui.get('bot').count(),1);ui.win.document.querySelector('aside').remove();await tick();assert.equal(ui.get('bot').count(),0);assert.equal(ui.root(),null);});


test('a reused overview mounts only after its asynchronous owner attribute matches the new selection',async t=>{const ui=await boot(t);ui.selection.set({currentAgentId:'group'});await tick();assert.equal(ui.root(),null);ui.win.document.querySelector('[data-beebot-library-host]').setAttribute('data-beebot-library-host','group');await tick();assert.ok(ui.root());ui.action().click();await tick();assert.equal(ui.calls[0][1],'group');assert.equal(ui.win.document.querySelector('textarea').value,'Third draft');});

test('pause and resume require the acknowledged store state; a resolved command alone cannot report success',async t=>{const ui=await boot(t);ui.get('bot').set({status:'ready',value:[{id:'custom',purpose:'proactive-followup',executionOwner:'local',isEnabled:true,trigger:{type:'cron'}}]});ui.runtime.automations.setEnabled=async()=>{};await tick();ui.action().click();await tick();assert.match(ui.root().textContent,/保存结果未确认/);assert.doesNotMatch(ui.root().textContent,/设置已保存/);assert.ok(ui.action().disabled);});
test('a local follow-up with an unsupported event trigger cannot be described as running or resumed',async t=>{const ui=await boot(t);ui.get('bot').set({status:'ready',value:[{id:'event',purpose:'proactive-followup',executionOwner:'local',isEnabled:false,trigger:{type:'slack'}}]});await tick();assert.match(ui.root().textContent,/需要定时触发/);assert.doesNotMatch(ui.root().textContent,/已开启/);assert.ok(ui.action().disabled);ui.action().click();await tick();assert.equal(ui.calls.length,0);});
